server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
    metadataMap:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# mysql/redis/rabbit service name used here. 
spring:
  datasource:
    initializationMode: ALWAYS
    url: "jdbc:mysql://mysql:3306/sc_database?useUnicode=true&characterEncoding=utf8"
    username: "springcloud"
    password: "{cipher}38b6dd6855bccf5682b4ca4762b278ce66421167be9d5ec4c919e4fb8e236cd4"
    driverClassName: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimumIdle: 1
      maximumPoolSize: 2
      idleTimeout: 600000
      maxLifetime: 1800000
  redis:
    host: redis
    port: 6379
  cache:
    type: REDIS
  rabbitmq:
    host: rabbit
    port: 5672
  security:
    user:
      name: user
      password: 123456
      roles: ACTUATOR
  cloud:
    config:
      # allow command line override
      allowOverride: true
      overrideSystemProperties: false
    stream:
      bindings:
        inputOrganization:
            destination: sc.organization.change.topic
            contentType: application/json
            group: license.group
    # Workaround circular reference: https://github.com/spring-projects/spring-boot/issues/13042
    refresh:
      refreshable: NONE
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    sender:
      # otherwise rabbit is used if available
      type: WEB

management:
  endpoints:
    web:
      exposure:
        include: "*"

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8901/auth/user
    client:
      clientId: eagleeye

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.gonwan.springcloud: DEBUG

application:
  organizationUrl: http://zuul-server/api/organization
