server:
  port: 5555

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  security:
    user:
      name: user
      password: 123456
      roles: ACTUATOR
  cloud:
    config:
      # allow command line override
      allowOverride: true
      overrideSystemProperties: false
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    sender:
      # otherwise rabbit is used if available
      type: WEB

management:
  endpoints:
    web:
      exposure:
        include: "*"

zuul:
  prefix: /api
  sensitiveHeaders: Cookie,Set-Cookie
  ignoredServices: "*"
  routes:
    authentication-service: /auth/**
    organization-service: /organization/**
    license-service: /license/**

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.gonwan.springcloud: DEBUG
