server:
  port: 5555

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  sleuth:
    sampler:
      percentage: 0.0
  zipkin:
    sender:
      # otherwise rabbit is used if available
      type: WEB

zuul:
  prefix: /api
  sensitiveHeaders: Cookie,Set-Cookie
  ignoredServices: "*"
  routes:
    authentication-service: /auth/**
    organization-service: /organization/**
    license-service: /license/**

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.gonwan.springcloud: DEBUG
