server:
  port: 9411

# https://stackoverflow.com/questions/39174579/how-to-configure-spring-cloud-zipkin-server-with-mysql-for-persistence
zipkin:
  storage:
    type: mysql

spring:
  config:
    # allow command line override
    allowOverride: true
    overrideSystemProperties: false
  datasource:
    initializationMode: ALWAYS
    schema: classpath:mysql.sql
    url: "jdbc:mysql://172.16.66.120:3306/sc_database?useUnicode=true&characterEncoding=utf8&autoReconnect=true&maxReconnects=3"
    username: "springcloud"
    password: "{cipher}38b6dd6855bccf5682b4ca4762b278ce66421167be9d5ec4c919e4fb8e236cd4"
    driverClassName: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimumIdle: 1
      maximumPoolSize: 2
      idleTimeout: 600000
      maxLifetime: 1800000
      #connectionTimeout: 30000  # overall connection timeout = connectionTimeout * maxReconnects, see DriverManager#setLoginTimeout().
  # Workaround circular reference: https://github.com/spring-projects/spring-boot/issues/13042
  cloud:
    refresh:
      refreshable: NONE

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.gonwan.springcloud: DEBUG
