global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    monitor: 'spring-cloud-demo'
scrape_configs:
- job_name: organization-service
  scrape_interval: 10s
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: [ 'organization-service:8085' ]
    labels:
      application: organization-app
      instance: organization-svc
  basic_auth:
    username: actuator
    password: actuator
- job_name: license-service
  scrape_interval: 10s
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: [ 'license-service:8080' ]
    labels:
      application: license-app
      instance: license-svc
  # - targets: [ 'license-service:8081' ]
  #   labels:
  #     application: license-app
  #     instance: license-svc1
  basic_auth:
    username: actuator
    password: actuator
