global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    monitor: 'spring-cloud-demo'
scrape_configs:
  - job_name: organization-service
    scrape_interval: 10s
    metrics_path: /actuator/prometheus
    static_configs:
    - targets: [ "organization-service:8085" ]
  - job_name: license-service
    scrape_interval: 10s
    metrics_path: /actuator/prometheus
    static_configs:
    - targets: [ "license-service:8080" ]
