server:
  port: 8901
  servlet:
    contextPath: /auth

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.gonwan.springcloud: DEBUG
