server:
  port: 8901
  servlet:
    contextPath: /auth

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  redis:
    host: 192.168.11.234
    port: 6379
  security:
    user:
      name: user
      password: 123456
      roles: ACTUATOR

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.gonwan.springcloud: DEBUG
