server:
  port: 8901
  servlet:
    contextPath: /auth

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      # allow command line override
      allowOverride: true
      overrideSystemProperties: false
  redis:
    host: 172.16.87.12
    port: 6379

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.gonwan.springcloud: DEBUG
