server:
  port: 8085

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    initializationMode: ALWAYS
    url: "jdbc:mysql://192.168.11.234:3306/sc_database?useUnicode=true&characterEncoding=utf8"
    username: "springcloud"
    password: "sc_passw0rd"
    driverClassName: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimumIdle: 1
      maximumPoolSize: 2
      idleTimeout: 600000
      maxLifetime: 1800000
  rabbitmq:
    host: 192.168.11.234
    port: 5672
  cloud:
    stream:
      bindings:
        output:
            destination: sc.organization.change.topic
            contentType: application/json
    # Workaround circular reference: https://github.com/spring-projects/spring-boot/issues/13042
    refresh:
      refreshable: NONE
  sleuth:
    sampler:
      probability: 0.0
  zipkin:
    sender:
      # otherwise rabbit is used if available
      type: WEB

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8901/auth/user

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.gonwan.springcloud: DEBUG
