## yum install docker-distribution
## system start docker-distribution
#
#I'd like to clarify that you should add the { "insecure-registries":["172.16.87.12:5000"] } to /etc/docker/daemon.json in the client machine.
## systemctl restart docker
#
## docker image tag gonwan/sc-zuul-server:2.0.0 172.16.87.12:5000/gonwan/sc-zuul-server:2.0.0
## docker push 172.16.87.12:5000/gonwan/sc-zuul-server:2.0.0
## docker pull 172.16.87.12:5000/gonwan/sc-zuul-server:2.0.0

apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: 172.16.87.12:5000/gonwan/sc-eureka-server:2.0.0
      ports:
        containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server-svc
  labels:
    app: eureka-server
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8761
    nodePort: 30001
  selector:
    app: eureka-server
